### ISSUE TITLE
Two case-different files INVSEP1.PNG and INVSEP1.png

### ISSUE THREAD

**Issue by tomasz1986** [dive-bomber/Classic-BG-UI#1]
The two files only differ in their case ("PNG" vs "png"). Is there any reason for it? Windows and macOS don't support case different filenames, so the repository as such cannot be used/saved in those systems (by default, without hacking around).

**Comment by dive-bomber** [comment]
Yeah, thanks for mentioning it, I removed one of them. I am not sure why there are differences (PNG vs png) at all, I would never done capital 'PNG' by myself, so probably default photoshop option (export as....).

I don't know how the old one even made it in there in the first place, it was from my experimentation from waaay back. I wanted to have hand-drawn underlines below categories' names, but I didn't like the final effect.

**Comment by tomasz1986** [comment]
Thank you for a super quick fix 👍.
